export const commonConcepts = [
  "Cuota de mantenimiento",
  "Cuota extraordinaria",
  "Seguridad",
  "Electricidad",
  "Limpieza",
  "Intereses por morosidad",
  "Uso de áreas comunes",
  "Agua",
  "Gas",
  "Fondo de reserva",
  "Reparaciones menores",
  "Recargos",
  "Alumbrado",
  "Convivencia",
  "Multa por ruido",
  "Multa por estacionamiento",
  "Mantenimiento de elevadores",
  "Cuota por mascotas",
  "Servicio de jardinería",
  "Pintura de áreas comunes",
  "Reparación de techos",
  "Inspección de sistemas eléctricos",
  "Mantenimiento de piscinas",
  "Renovación de contratos de servicios",
  "Mantenimiento de sistemas de ventilación",
  "Seguro del edificio",
  "Impuesto predial",
  "Aseo de áreas externas",
  "Mantenimiento de cámaras de vigilancia",
  "Contador de agua y gas",
  "Suministro de productos de limpieza",
  "Gastos administrativos",
  "Sistemas de control de acceso",
  "Reemplazo de cerraduras",
  "Mantenimiento de sistemas de drenaje",
  "Monitoreo de seguridad",
  "Mantenimiento de parques infantiles",
  "Reciclaje",
  "Cuota por reparación de infraestructura",
  "Pavimentación de caminos internos",
  "Servicios de mensajería y paquetería",
  "Alquiler de espacios comunes para eventos",
  "Servicios de internet común",
  "Mantenimiento de sistemas de calefacción",
  "Servicios de agua potable de emergencia",
  "Cuota de reparación de fachada",
  "Proyectos de mejora o expansión",
  "Costos por reuniones extraordinarias",
];
