export const commonAreas = [
  "Alberca",
  "Área de Artes Marciales",
  "Área de BBQ",
  "Área de Crossfit",
  "Área de Ejercicio al Aire Libre",
  "Área de Juegos Infantiles",
  "Área de Lavado",
  "Área de Mascotas",
  "Área de Meditación",
  "Área de Picnic",
  "Área de Pilates",
  "Área de Ping Pong",
  "Área de Trabajo Compartido",
  "Área de Yoga",
  "Asador",
  "Biblioteca",
  "Cancha de Básquetbol",
  "Cancha de Fútbol",
  "Cancha de Padel",
  "Cancha de Squash",
  "Cancha de Tenis",
  "Cancha de Voleibol",
  "Estacionamiento de Visitantes",
  "Gimnasio",
  "Huerto Comunitario",
  "Jacuzzi",
  "Jardín",
  "Pista de Trote",
  "Sala de Billar",
  "Sala de Cine",
  "Sala de Danza",
  "Sala de Estudio",
  "Sala de Juegos",
  "Sala de Masajes",
  "Sala de Música",
  "Salón de Eventos",
  "Salón de Fiestas",
  "Salón de Reuniones",
  "Salón de Usos Múltiples",
  "Sauna",
  "Spa",
  "Terraza",
];
