export const EXPENSE_CONCEPTS = [
    "Caja Chica", "Agua", "Luz", "Internet", "Teléfono", "Jardinería", "Limpieza",
    "Mantenimiento de Elevadores", "Seguridad Privada", "Pintura General", "Reparaciones Varias",
    "Papelería y Suministros", "Honorarios de Contador", "Honorarios de Abogado", "Publicidad",
    "Gas", "Servicios de Plomería", "Servicios de Electricidad", "Sistema de Alarma", "Póliza de Seguro",
    "Mobiliario", "Equipo de Cómputo", "Alquiler de Salón", "Servicio de Basura", "Honorarios de Administración",
    "Pago de Impuestos", "Material de Construcción", "Servicio de Cerrajería", "Reparación de Bombas de Agua",
    "Artículos de Limpieza",
    "Mantenimiento de Piscina",
    "Mantenimiento de Áreas Verdes",
    "Sistema de Vigilancia",
    "Mantenimiento de Estacionamiento",
    "Fumigación y Control de Plagas",
    "Mantenimiento de Gimnasio",
    "Reemplazo de Luminarias",
    "Mantenimiento de Portones Eléctricos",
    "Sistema de Intercomunicación",
    "Impermeabilización",
    "Renovación de Extintores y Equipos Contra Incendios",
    "Instalación y Mantenimiento de Paneles Solares",
    "Capacitación y Formación del Personal de Seguridad",
    "Mantenimiento de Sistemas de Climatización",
    "Reparación y Sellado de Techos y Canaletas",
    "Control de Accesos Digitales (Llaves y Tarjetas Inteligentes)",
    "Señalización y Señales de Evacuación",
    "Sistemas de Riego Automatizado para Áreas Verdes",
    "Diseño y Remodelación de Áreas Comunes",
    "Adquisición de Herramientas y Maquinaria para Mantenimiento",
    "Otros"
];